Repository creare-com/podpac, pull requests merged in 2019-09, with the labels that each got.

#306 FIX: automation of lambda creation, upload, and configuration (as muc…
  .gitignore
  dist/aws/Dockerfile
  dist/aws/_mk_dist.py
  dist/aws/build_lambda.sh
  dist/aws/configure_lambda.sh
  dist/aws/handler.py
  dist/aws/link_so.py
  dist/aws/mk_dist.py
  dist/aws/print_logs.sh
  dist/aws/upload_lambda.sh
  podpac/core/settings.py
  podpac/version.py
Labels: 2H

#315 general readonly tag
  podpac/core/data/datasource.py
  podpac/core/data/test/test_interpolate.py
  podpac/core/data/test/test_types.py
  podpac/core/data/types.py
  podpac/core/node.py
  podpac/core/test/test_node.py
  podpac/datalib/gfs.py
  podpac/datalib/intake.py
  podpac/datalib/smap.py
  podpac/datalib/terraintiles.py
Labels: enhancement

#314 Tests should run without warnings.
  podpac/core/algorithm/stats.py
  podpac/core/cache/test/test_cache_stores.py
  podpac/core/coordinates/test/test_coordinates.py
  podpac/core/coordinates/test/test_uniform_coordinates1d.py
  podpac/core/coordinates/uniform_coordinates1d.py
  podpac/core/data/interpolation.py
  podpac/core/data/interpolator.py
  podpac/core/data/interpolators.py
  podpac/core/data/test/test_datasource.py
  podpac/core/data/test/test_types.py
  setup.cfg
Labels: fixes-and-maintenance
