Repository creare-com/podpac, pull requests merged in 2020-04, with the labels that each got.

#387 Bugfix: compositor auto_outputs flag
  podpac/core/compositor/compositor.py
  podpac/core/compositor/test/test_base_compositor.py
  podpac/core/compositor/test/test_ordered_compositor.py
  podpac/datalib/cosmos_stations.py
  podpac/datalib/smap.py
Labels: bug, discussion

#389 node definition loops and caching
  podpac/core/cache/cache_ctrl.py
  podpac/core/cache/cache_store.py
  podpac/core/cache/file_cache_store.py
  podpac/core/cache/ram_cache_store.py
  podpac/core/cache/test/test_cache_ctrl.py
  podpac/core/cache/test/test_cache_stores.py
  podpac/core/data/csv_source.py
  podpac/core/data/file_source.py
  podpac/core/data/ogc.py
  podpac/core/data/test/test_csv.py
  podpac/core/data/test/test_file_source.py
  podpac/core/node.py
  podpac/core/test/test_node.py
Labels: bug, enhancement, fixes-and-maintenance, testing

#386 Feature/cosmos stations
  podpac/algorithm.py
  podpac/core/algorithm/stats.py
  podpac/core/algorithm/test/test_stats.py
  podpac/core/compositor/compositor.py
  podpac/core/compositor/test/test_base_compositor.py
  podpac/core/compositor/test/test_ordered_compositor.py
  podpac/core/interpolation/interpolator.py
  podpac/datalib/cosmos_stations.py
  podpac/datalib/smap.py
Labels: enhancement

#381 Feature/parallel manager wip
  .travis.yml
  dist/aws/handler.py
  doc/source/cache.md
  doc/source/coordinates.md
  doc/source/install.md
  doc/source/specs/nodes.md
  podpac/alglib/__init__.py
  podpac/alglib/climatology.py
  podpac/core/algorithm/algorithm.py
  podpac/core/algorithm/coord_select.py
  podpac/core/algorithm/stats.py
  podpac/core/algorithm/test/test_stats.py
  podpac/core/authentication.py
  podpac/core/coordinates/coordinates.py
  podpac/core/data/file_source.py
  podpac/core/data/zarr_source.py
  podpac/core/managers/aws.py
  podpac/core/managers/multi_process.py
  podpac/core/managers/parallel.py
  podpac/core/managers/test/test_multiprocess.py
  podpac/core/managers/test/test_multithreading.py
  podpac/core/managers/test/test_parallel.py
  podpac/core/units.py
  podpac/core/utils.py
  podpac/datalib/gfs.py
  podpac/datalib/smap.py
  podpac/managers.py
  pyproject.toml
Labels: 32H, enhancement

#391 ENH: Add podpac version to node definition.
  podpac/core/algorithm/generic.py
  podpac/core/node.py
  podpac/core/test/test_node.py
  podpac/core/utils.py
Labels: enhancement

#396 Feature/uniform coords transform to uniform
  podpac/core/coordinates/array_coordinates1d.py
  podpac/core/coordinates/coordinates.py
  podpac/core/coordinates/coordinates1d.py
  podpac/core/coordinates/dependent_coordinates.py
  podpac/core/coordinates/stacked_coordinates.py
  podpac/core/coordinates/test/test_coordinates.py
  podpac/core/coordinates/test/test_uniform_coordinates1d.py
  podpac/core/coordinates/uniform_coordinates1d.py
  podpac/core/data/test/test_datasource.py
Labels: enhancement
