Repository creare-com/podpac, pull requests merged in 2020-10, with the labels that each got.

#425 FIX: Exception when bounds are lower precision than coordinates
  podpac/core/coordinates/array_coordinates1d.py
  podpac/core/coordinates/test/test_coordinates.py
  podpac/core/coordinates/test/test_coordinates_utils.py
  podpac/core/coordinates/utils.py
Labels: bug, confirmed

#426 ENH/MAINT: Feature/interpolation refactor
  doc/source/api.rst
  podpac/algorithm.py
  podpac/core/algorithm/algorithm.py
  podpac/core/algorithm/coord_select.py
  podpac/core/algorithm/reprojection.py
  podpac/core/algorithm/signal.py
  podpac/core/algorithm/stats.py
  podpac/core/algorithm/test/test_reprojection.py
  podpac/core/compositor/compositor.py
  podpac/core/compositor/data_compositor.py
  podpac/core/compositor/test/test_tile_compositor.py
  podpac/core/coordinates/coordinates.py
  podpac/core/data/array_source.py
  podpac/core/data/csv_source.py
  podpac/core/data/dataset_source.py
  podpac/core/data/datasource.py
  podpac/core/data/h5py_source.py
  podpac/core/data/ogc.py
  podpac/core/data/pydap_source.py
  podpac/core/data/rasterio_source.py
  podpac/core/data/reprojection.py
  podpac/core/data/test/test_datasource.py
  podpac/core/data/zarr_source.py
  podpac/core/interpolation/interpolation.py
  podpac/core/interpolation/interpolation_manager.py
  podpac/core/interpolation/interpolators.py
  podpac/core/interpolation/test/test_interpolation.py
  podpac/core/interpolation/test/test_interpolation_manager.py
  podpac/core/interpolation/test/test_interpolators.py
  podpac/core/managers/aws.py
  podpac/core/managers/multi_process.py
  podpac/core/managers/parallel.py
  podpac/core/node.py
  podpac/core/test/test_node.py
  podpac/data.py
  podpac/datalib/egi.py
  podpac/datalib/satutils.py
  podpac/interpolators.py
Labels: enhancement, fixes-and-maintenance

#429 Clean up DataSource debug attributes
  podpac/core/data/datasource.py
Labels: fixes-and-maintenance

#431 WCS + soilgrids
  podpac/core/coordinates/coordinates.py
  podpac/core/data/datasource.py
  podpac/core/data/ogc.py
  podpac/core/data/test/test_wcs.py
  podpac/datalib/soilgrids.py
  setup.py
Labels: enhancement, fixes-and-maintenance
