Repository creare-com/podpac, pull requests merged in 2021-04, with the labels that each got.

#455 BUGFIX: Nearest Preview Select Coordinates
  podpac/core/interpolation/interpolation_manager.py
  podpac/core/interpolation/nearest_neighbor_interpolator.py
  podpac/core/interpolation/test/test_interpolators.py
Labels: bug

#462 Specify reprojection dims and intersect with requested coordinates.
  podpac/core/algorithm/reprojection.py
Labels: enhancement

#463 Feature/node probe
  .travis.yml
  podpac/core/interpolation/interpolation.py
  podpac/core/node.py
  podpac/core/test/test_utils.py
  podpac/core/utils.py
Labels: enhancement

#470 Replace Style enumeration tuple traits with dict traits.
  podpac/core/style.py
  podpac/core/test/test_style.py
  podpac/datalib/drought_monitor.py
Labels: backwards-incompatible

#473 FIX: Use abs. value for step comparison
  podpac/core/interpolation/nearest_neighbor_interpolator.py
  podpac/core/interpolation/selector.py
  podpac/core/interpolation/test/test_selector.py
Labels: bug

#474 FIX: Fixing reproject merge_dims error.
  podpac/core/algorithm/reprojection.py
  podpac/core/algorithm/test/test_reprojection.py
Labels: bug
